---
# Default variables for tls-certs role — operator-overrideable
tls_cert_dir: /etc/kafka/ssl
tls_ca_cn: KafkaLabCA
tls_ca_ou: KafkaLab
tls_ca_o: KafkaLab
tls_ca_c: US
tls_ca_validity_days: 3650
tls_node_validity_days: 365
tls_keystore_password: "{{ vault_tls_keystore_password | default('changeit') }}"
tls_truststore_password: "{{ vault_tls_truststore_password | default('changeit') }}"
tls_key_password: "{{ vault_tls_key_password | default('changeit') }}"
tls_ca_password: "{{ vault_tls_ca_password | default('changeit') }}"
tls_key_size: 2048
tls_key_algorithm: RSA
tls_dns_domain: kafkalab.internal
tls_local_cert_dir: /opt/confluent/tls-staging
