---
plugin: azure.azcollection.azure_rm
auth_source: msi
include_vm_resource_groups:
  - klc-rg-kafkalab-scus
keyed_groups:
  - prefix: ''
    separator: ''
    key: tags.component | default('ungrouped')
  - prefix: ''
    separator: ''
    key: tags.environment | default('ungrouped')
  - prefix: ''
    separator: ''
    key: tags.region | default('ungrouped')
compose:
  ansible_host: private_ipv4_addresses[0]
  ansible_user: "'azureuser'"
