---
# Kafka Connect service tasks
- name: Create GC log directory
  ansible.builtin.file:
    path: '/var/log/kafka-connect'
    state: directory
    owner: '{{ kafka_user }}'
    group: '{{ kafka_group }}'
    mode: '0755'
  become: true

- name: Deploy confluent-kafka-connect systemd unit
  ansible.builtin.template:
    src: 'confluent-kafka-connect.service.j2'
    dest: '/etc/systemd/system/confluent-kafka-connect.service'
    owner: root
    group: root
    mode: '0644'
  become: true
  notify: 'Restart confluent-kafka-connect'

- name: Enable and start confluent-kafka-connect service
  ansible.builtin.systemd:
    name: '{{ kafka_connect_service_name }}'
    enabled: true
    state: started
    daemon_reload: true
  become: true
